type User {
  id: ID!
  name: String!
  email: String!
}

type Task {
  id: ID!
  title: String!
  description: String
  owner: User
}

type CalendarEvent {
  id: ID!
  title: String!
  start: String!
  end: String!
  providerId: String
}

type Query {
  ping: String!
  tasks(ownerId: ID): [Task!]!
  events(ownerId: ID): [CalendarEvent!]!
  users: [User!]!
}

input CreateTaskInput {
  title: String!
  description: String
  ownerId: ID
}

type Mutation {
  createTask(input: CreateTaskInput!): Task!
  splitTaskToEvents(taskId: ID!): [CalendarEvent!]!
}

schema {
  query: Query
  mutation: Mutation
}
